[tool.poetry]
name = "goit-homework-"
version = "0.1.0"
description = ""
authors = ["KarinaNester <liubatskakarina@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
